version: '3'

services:
  pdferrors-django:

    build: ./pdflist
    expose:
     - "8888"
    command: sh -c 'python3 manage.py makemigrations && python3 manage.py migrate --run-syncdb && python3 createsuperuser.py && python3 eventmanager.py & gunicorn mydjango.wsgi:application -w 2 -b :8888'
    working_dir: /data/pdflist/mydjango
    environment:
      - CREATE_SUPER_USER=${CREATE_SUPER_USER}
      - SUPER_USER=${SUPER_USER}
      - SUPER_USER_PASSWORD=${SUPER_USER_PASSWORD}
      - SUPER_USER_EMAIL=${SUPER_USER_EMAIL}
      - DB_NAME=${PDFERROR_DB_NAME}
      - DB_USER=${PDFERROR_DB_USER}
      - DB_PASS=${PDFERROR_DB_PASS}
      - DB_SERVICE=${PDFERROR_DB_SERVICE}
      - DB_PORT=${PDFERROR_DB_PORT}
    volumes:
      - ./pdflist:/data/pdflist
    
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=8888"
      - "traefik.frontend.rule=Host:pdf.lbr.lu"
      - "traefik.frontend.entryPoints=http"
    depends_on:
      - postgres-pdf
    networks:
      - web
    restart: always


  postgres-pdf:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${PDFERROR_DB_NAME}
      - POSTGRES_USER=${PDFERROR_DB_USER}
      - POSTGRES_PASSWORD=${PDFERROR_DB_PASS}
    labels:
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:pdfdb.lbr.lu"
      - "traefik.enable=true"
      - "traefik.port=5432"
      - "traefik.frontend.entryPoints=http"
    networks:
      - web

    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    expose:
      - "5432"

  poll-errors-intranet:
    build: ./pdferror
    restart: always
    environment:
      - IAM_USER=${IAM_USER}
      - IAM_PASSWORD=${IAM_PASSWORD}
      - FLASK_REDIS_HOST=redis
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=5000"  
    networks:
      - web
networks:
  web:
    external: true
  
